version: '3'
services:


  admin:
    image: datech-demo/admin:1.0
    restart: always
    volumes:
      - ./logs:/u01/application-logs/admin
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    ports:
      - "9200:9200"
    networks:
      - network



networks:
  network:
    external: true
    name: admin-network



